88 Classes e  Componentes
UnBArqDsw/2020.1_G12_Stock pull request #100
Opened 2020-09-24 16:46 UTC by micaellagouveia

## Descrição 

Diagramação e documentação das classes e componentes, além do relato do dia da reunião

## Resolve (Issues)

Issue #88 

## Tarefas gerais realizadas
* Diagramação das classes e componentes
* Documentação da diagrams sprint
* Atualização dos dias de treinamento e planejamento sprint 4 (mudança do dia da sofia e do gabriel davi)
* Adição das gravações

2020-09-24 17:12 UTC, sofiapatrocinio requested changes

2020-09-24 17:12 UTC, sofiapatrocinio commented on docs/Modeling/Diagrams/Diagrams.md
> +2. **Produzir**: Essa é a maior fase da reunião, sendo ela destinada para a produção do que for necessário para a diagramação. Como são diagramas com finalidades distintas, essa fase se torna livre d
"técnica" está escrito errado

2020-09-24 17:13 UTC, sofiapatrocinio commented
O vídeo de diagrama de classes está quebrado
![image](https://user-images.githubusercontent.com/38709421/94177518-09a7b700-fe70-11ea-98ec-a3f8ecd7dc53.png)

2020-09-24 19:58 UTC, micaellagouveia commented
> O vídeo de diagrama de classes está quebrado
> ![image](https://user-images.githubusercontent.com/38709421/94177518-09a7b700-fe70-11ea-98ec-a3f8ecd7dc53.png)

Coloquei o link certo, ele ainda ta sendo processado mas ta acessando o lugar certo.

2020-09-25 00:05 UTC, pedroeagle approved these changes

2020-09-25 00:10 UTC, sofiapatrocinio approved these changes

2020-09-25 00:12 UTC, pedroeagle approved these changes

2020-09-25 00:13 UTC, merged