93 casos de uso
UnBArqDsw/2020.1_G12_Stock pull request #124
Opened 2020-10-02 12:45 UTC by micaellagouveia

## Descrição 

Criação dos casos de uso e seus diagramas

## Resolve (Issues)

Issue #93 

## Tarefas gerais realizadas
* Criação dos casos de uso
* Criação dos diagramas
* Documentação na WIki

2020-10-02 16:26 UTC, sofiapatrocinio requested changes

2020-10-02 16:26 UTC, sofiapatrocinio commented on docs/Modeling/CasosUso/casos/caso10.md
> +    2. O [usuário Owner](Modeling/objeto?id=Owner)/[Admin](Modeling/objeto?id=Admin) deve entrar na tela de [Estoque](Modeling/objeto?  id=Estoque).
tem um espaço desnecessário aqui

2020-10-02 16:26 UTC, sofiapatrocinio commented on docs/Modeling/CasosUso/casos/caso10.md
> +    4. O [usuário Owner](Modeling/objeto?id=Owner)/[Admin](Modeling/objeto?id=Admin) deve selecionar o botão de "Adicionar Categoria".
Categoria é um léxico equivalente à tag

2020-10-03 00:29 UTC, sofiapatrocinio approved these changes

2020-10-03 12:31 UTC, pedroeagle approved these changes

2020-10-03 12:40 UTC, gitgabiru approved these changes

2020-10-03 12:45 UTC, merged