[WIP] Docsify
UnBArqDsw/2020.1_G12_Stock pull request #13
Opened 2020-08-25 02:16 UTC by GabrielDVpereira

## Description 

I have Implemented the building blocks of what's gonna be our wiki page. 

## Resolve (Issues)

#12 - Docsify

## Tasks
* Set the docsify
* Styled the cover page
* Styled the sidebar
* Create a member page and project's description. 

## Testing 
in order to test this PR, you have to go to the page /docs and then run "docsify serve". The server will be up on localhost:3000.

2020-08-25 12:10 UTC, sofiapatrocinio requested changes

2020-08-25 12:10 UTC, sofiapatrocinio commented on README.md
>  **Conteúdo da Disciplina**: XXXXXXXXXX<br>
Falei com a Milene e o conteúdo é o código da disciplina, alterar para Código da disciplina é FGA0208-T01.

2020-08-25 12:10 UTC, sofiapatrocinio commented on docs/_sidebar.md
> +  - [- Pré-rastriabilidade](/)
Pré-rastreabilidade tá escrito errado

2020-08-25 12:10 UTC, sofiapatrocinio commented on docs/_sidebar.md
> +    - [- rich picture](/)
Podiamos padronizar as técnicas todas em Camel Case

2020-08-25 12:11 UTC, sofiapatrocinio commented
Tem como tirar esse menu sanduiche? Quando clica nele tá bugando
![Screenshot from 2020-08-25 09-09-02](https://user-images.githubusercontent.com/38709421/91172653-e5ab5700-e6b2-11ea-8a13-40efa72a6730.png)

De resto, ficou bonitão!

2020-08-25 12:31 UTC, micaellagouveia requested changes

2020-08-25 12:31 UTC, micaellagouveia commented on docs/README.md
> +      <p>Micaela Gouveia<p>
Só um errinho aqui, Micaela é com dois Ls, então é Micaella.

2020-08-25 12:31 UTC, micaellagouveia commented on docs/README.md
> +    <div class="member">
Será que tinha como deixar os dois integrantes que ficaram embaixo centralizados? Pra não ficar esse espaço restante.
![membros](https://user-images.githubusercontent.com/48630408/91174413-9b77a500-e6b5-11ea-9105-31336ccb7d7a.png)

2020-08-25 12:33 UTC, micaellagouveia requested changes

2020-08-25 12:33 UTC, micaellagouveia commented on docs/_sidebar.md
> +  - [- Pré-rastriabilidade](/)
Pré-rastreabilidade ficou com um hífen(-) que não tem nos outros tópicos abaixo(como modelgaem e elicitação)

2020-08-25 19:38 UTC, pedroeagle approved these changes
Ficou bonitão mesmo, só corrigir os probleminhas que a Micaella e a Sofia mencionaram.

2020-08-25 19:49 UTC, GabrielDVpereira commented on docs/README.md
> +    <div class="member">
![image](https://user-images.githubusercontent.com/37307099/91220679-e368ed00-e6f2-11ea-94ff-4b01077d883b.png)
:)

2020-08-25 20:44 UTC, gitgabiru approved these changes

2020-08-25 21:19 UTC, sofiapatrocinio approved these changes

2020-08-26 01:10 UTC, micaellagouveia approved these changes

2020-08-26 01:11 UTC, merged