113 grasp
UnBArqDsw/2020.1_G12_Stock pull request #137
Opened 2020-10-03 22:22 UTC by sofiapatrocinio

## Descrição 

Adição da documentação de GRASP

## Resolve (Issues)

#113 

## Tarefas gerais realizadas
* Documentação GRASP com base no Estudo Dirigido

2020-10-03 22:32 UTC, micaellagouveia requested changes
Ficou ótimo !!!!

2020-10-03 22:32 UTC, micaellagouveia commented on docs/Project/Estudos/GRASP.md
> +| 03/10/2020 | 1.3 | Adição dos pontos positivos e negativos e documentos pra refatoração | Sofia Patrocínio |
para ao invés de pra

2020-10-03 22:32 UTC, micaellagouveia commented on docs/Project/Estudos/GRASP.md
> +Ao avaliar o modelo, primeiro questionamento é quais classes possuem as responsabilidades de criar instâncias. Seu objetivo é definir como criador o objeto que precise ser conectado ao objeto criado
... definir como criador o objeto ..., acho que falta uma vígula: ... definir, como criador, o objeto.

2020-10-03 22:32 UTC, micaellagouveia commented on docs/Project/Estudos/GRASP.md
> +- Uma matriz multidimensional onde as linhas / colunas têm tamanhos diferentes,tratando um ponteiro de cabeça da mesma forma que um ponteiro em um registro.
espaço entre a vígula e a palavra tratando

2020-10-04 00:01 UTC, micaellagouveia approved these changes

2020-10-04 02:04 UTC, pedroeagle approved these changes

2020-10-04 02:21 UTC, merged