Estudo - GoF Estrutural 2
UnBArqDsw/2020.1_G12_Stock pull request #138
Opened 2020-10-04 18:28 UTC by GabrielDVpereira

## Descrição 

Adição dos demais padrões de projeto 

## Resolve (Issues)

#116

2020-10-05 13:06 UTC, micaellagouveia requested changes
Ficou muito bommm!!!

2020-10-05 13:06 UTC, micaellagouveia commented on docs/Project/Estudos/estrutural.md
> +O método de flyweight é uma otimização. Ele vem para solucionar o problemas de gerenciamento de memória em programas que consomem muito RAM durante sua execução devido ao uso repetitivo de um objeto
... solucionar o problema .... ou ... os problemas ...

2020-10-05 13:06 UTC, micaellagouveia commented on docs/Project/Estudos/estrutural.md
> +Sim, o proxy possui diversos usos e por isso poderia ser aplicado em nosso projeto. Por exemplo, para limitar o numero de chamadas da criação de produtos em estoque, proteger algumas rotas do sistema
número está sem acento

2020-10-05 13:06 UTC, micaellagouveia commented on docs/Project/Estudos/estrutural.md
> +Sim, o proxy possui diversos usos e por isso poderia ser aplicado em nosso projeto. Por exemplo, para limitar o numero de chamadas da criação de produtos em estoque, proteger algumas rotas do sistema
chamadas excessivas está escrito chamadas excessiva.

2020-10-05 13:06 UTC, micaellagouveia commented on docs/Project/Estudos/estrutural.md
> +Sim, um lugar em que seria uma ótima oportunida de para adição de decorators seria na classe de análise que retorna dos dados para a geração de gráficos em nossa aplicação. Com isso, se for necessári
oportunidade está escrito oportunida

2020-10-05 13:06 UTC, micaellagouveia commented on docs/Project/Estudos/estrutural.md
> +De certa forma, já usamos esse padrão quando separamos as categorias em uma classe separadad e produto e também para o tipo de feedback.
sparada está escrito separadad

2020-10-05 13:06 UTC, micaellagouveia commented on docs/Project/Estudos/estrutural.md
> +Não iremos, a princípio, utilizar bibliotecas complexas a ponto de se fazer necessário a utilização desse padrão
não é necessário o uso de vírgulas entre a princípio.

2020-10-05 18:53 UTC, sofiapatrocinio requested changes

2020-10-05 18:53 UTC, sofiapatrocinio commented on docs/Project/Estudos/estrutural.md
> +Um dos fatores que afetam o custo de manutenção/evolução de um sistema é a dependência gerada na interação entre os objetos desse sistema. Os padrões de projeto estruturais tem o objetivo de diminiui
"diminuir" tá escrito errado

2020-10-05 18:53 UTC, sofiapatrocinio commented on docs/Project/Estudos/estrutural.md
> +- Diagrama de sequência: Nesse caso, o feedback não chamaria o typeFeedback e sim o método da factory que guarda todas as instâncias de typeFeedck, passando somente suas especificações de qual type d
"typeFeedback" tá escrito errado

2020-10-05 18:53 UTC, sofiapatrocinio commented on docs/Project/Estudos/estrutural.md
> +- Resposta final para o setvidor pode demorar mais tempo.
"servidor" tá escrito errado

2020-10-05 18:53 UTC, sofiapatrocinio commented on docs/Project/Estudos/estrutural.md
> +Sim, o proxy possui diversos usos e por isso poderia ser aplicado em nosso projeto. Por exemplo, para limitar o número de chamadas da criação de produtos em estoque, proteger algumas rotas do sistema
"possibilidade" tá escrito errado

2020-10-05 18:53 UTC, sofiapatrocinio commented on docs/Project/Estudos/estrutural.md
> +- Podemos extender comportamento de objetos sem precisar criar novas subclasses.
"estender" tá escrito errado

2020-10-05 18:53 UTC, sofiapatrocinio commented on docs/Project/Estudos/estrutural.md
> +Esse padrão permite a divisão de uma classe em implementações menores que podem ser desenvolvidas indenpendentes umas das outras.
"independentes" tá escrito errado

2020-10-05 18:53 UTC, sofiapatrocinio commented on docs/Project/Estudos/estrutural.md
> +Aqui, podemos ver que há uma separação em uma interface de algum parametro ou atributo. O bridge é bem simples porém muito eficaz pois possibilita a adição e modificação de quantas classes forem nece
Falta um acento em "parametro"

2020-10-07 00:55 UTC, sofiapatrocinio requested changes

2020-10-07 00:55 UTC, sofiapatrocinio commented on docs/Project/Estudos/estrutural.md
> +Sim, um lugar em que seria uma ótima oportunidade de para adição de decorators seria na classe de análise que retorna dos dados para a geração de gráficos em nossa aplicação. Com isso, se for necessá
"estender" tá escrito errado

2020-10-08 01:44 UTC, micaellagouveia approved these changes

2020-10-08 01:45 UTC, sofiapatrocinio approved these changes

2020-10-08 01:45 UTC, merged