#11 Argumentação
UnBArqDsw/2020.1_G12_Stock pull request #14
Opened 2020-08-28 13:00 UTC by pedroeagle

Adicionamos uma primeira versão da argumentação nos baseando na Wiki do projeto PAX e em alguns embasamentos teóricos para a utilização das técnicas. Está tudo referenciado ao final do documento. O documento já está devidamente inserido nas rotas da Wiki.

Close #11

2020-08-28 17:18 UTC, sofiapatrocinio approved these changes

2020-08-28 20:26 UTC, GabrielDVpereira approved these changes

2020-08-28 21:28 UTC, micaellagouveia requested changes
Pedi uma alteração em um detalhe pequeno, mas ficou ótimo galera!

2020-08-28 21:28 UTC, micaellagouveia commented on docs/preTraceability/Argumentacao.md
> +| 27/08/2020 |  1.1   |  Adicionando definição de Argumentação | Gabriel Alves |
Acho que fica melhor Adição da definição de Argumentação, para poder padronizar.

2020-08-28 21:28 UTC, micaellagouveia commented on docs/preTraceability/Argumentacao.md
> +| 27/08/2020 |  1.2   |  Adicionando diagrama ACE em aplicação de controle de estoque e atualizando Referências | Gabriel Alves |
Acho que fica melhor Adição do diagrama, ao invés de adicionando, para ficar padronizado.

2020-08-28 21:28 UTC, micaellagouveia commented on docs/preTraceability/Argumentacao.md
> +| 28/08/2020 |  1.3   |  Adicionando resultado da votação e formatando conteúdo da página. | Pedro Igor |
Acho que fica melhor adição do resultado da votação para manter o padrão estabelecido.

2020-08-28 21:35 UTC, micaellagouveia requested changes

2020-08-28 21:35 UTC, micaellagouveia commented on docs/preTraceability/Argumentacao.md
> +Com isso, abaixo mostramos os argumetos, que levaram o grupo a escolha do tema deste projeto.
"argumetos" está com um erro de digitação.

2020-08-29 05:32 UTC, gitgabiru approved these changes
Perfeito Micaella, ficou bem melhor mesmo :)

2020-08-29 05:35 UTC, gitgabiru approved these changes

2020-08-29 13:47 UTC, micaellagouveia approved these changes

2020-08-29 13:47 UTC, merged