119 escolha tecnologias
UnBArqDsw/2020.1_G12_Stock pull request #152
Opened 2020-10-10 23:24 UTC by gitgabiru

## Descrição 

Descrição da arquitetura usada juntamente com as tecnologias

## Resolve (Issues)

#119 Escolha das tecnologias

## Tarefas gerais realizadas
* Padrão arquitetural
* Tecnologia de Back End
* Tecnologia de Front End

2020-10-10 23:55 UTC, micaellagouveia requested changes

2020-10-10 23:55 UTC, micaellagouveia commented on docs/Modeling/DescricaoArquitetural.md
> +### Back End
Faltou falar do sequelize

2020-10-10 23:55 UTC, micaellagouveia commented on docs/Index/modelingIndex.md
> +  - [Descrição Arquitetural](../Modeling/DescricaoArquitetural.md)
Colocar os ../ quebra na master. Pode deixar sem

2020-10-11 01:34 UTC, sofiapatrocinio approved these changes

2020-10-11 02:55 UTC, micaellagouveia approved these changes

2020-10-11 02:55 UTC, merged