#129 - refactor activity diagram
UnBArqDsw/2020.1_G12_Stock pull request #155
Opened 2020-10-15 13:24 UTC by GabrielDVpereira

## Descrição 

Refatoração dos diagramas de atividade de acordo com o feedback da professora

## Resolve (Issues)

#129

2020-10-15 14:16 UTC, micaellagouveia requested changes

2020-10-15 14:16 UTC, micaellagouveia commented on docs/Modeling/Diagrams/Atividades.md
>  ### Prazo de validade (V.0)
Como padrão estamos colocando as versões mais atuais por cima, então tem que colocar o v1 primeiro e depois o v0

2020-10-15 14:16 UTC, micaellagouveia commented on docs/Modeling/Diagrams/Atividades.md
>  ### Feedback(V.0)
Como padrão estamos colocando as versões mais atuais por cima, então tem que colocar o v1 primeiro e depois o v0

2020-10-15 14:16 UTC, micaellagouveia commented on docs/Modeling/Diagrams/Atividades.md
>  ### Consultar produto(V.0)
Como padrão estamos colocando as versões mais atuais por cima, então tem que colocar o v1 primeiro e depois o v0

2020-10-15 14:16 UTC, micaellagouveia commented on docs/Modeling/Diagrams/Atividades.md
>  ### Autenticar no sistema(V.0)
Como padrão estamos colocando as versões mais atuais por cima, então tem que colocar o v1 primeiro e depois o v0

2020-10-15 14:16 UTC, micaellagouveia commented on docs/Modeling/Diagrams/Atividades.md
>  ### Adicionar produto(V.0)
Como padrão estamos colocando as versões mais atuais por cima, então tem que colocar o v1 primeiro e depois o v0

2020-10-15 14:16 UTC, micaellagouveia commented on docs/Modeling/Diagrams/Atividades.md
>  ### Adicionar colaborador(V.0)
Como padrão estamos colocando as versões mais atuais por cima, então tem que colocar o v1 primeiro e depois o v0

2020-10-17 11:28 UTC, pedroeagle approved these changes

2020-10-17 12:02 UTC, micaellagouveia approved these changes

2020-10-17 12:03 UTC, merged