Cadeia de Responsabilidade
UnBArqDsw/2020.1_G12_Stock pull request #157
Opened 2020-10-16 15:33 UTC by micaellagouveia

## Descrição 

Documentação sobre o padrão da cadeia de responsabilidade.

## Resolve (Issues)

Padrão encontrado como possível solução da hierarquia dos usuários, dificuldade encontrada na issue #147 

## PRs relacionados, se houver

Haverá pr no back também

2020-10-16 23:59 UTC, sofiapatrocinio requested changes

2020-10-16 23:59 UTC, sofiapatrocinio commented on docs/Project/Estudos/comportamental.md
> +* Aplica o princípio da resposabilidade única.
'responsabilidade' tá escrito errado

2020-10-17 11:24 UTC, pedroeagle approved these changes

2020-10-17 12:04 UTC, sofiapatrocinio approved these changes

2020-10-17 12:04 UTC, sofiapatrocinio approved these changes

2020-10-17 12:04 UTC, merged