Adição dos storyboards no git
UnBArqDsw/2020.1_G12_Stock pull request #18
Opened 2020-08-31 01:56 UTC by GabrielDVpereira

## Description 
Criação da página dos storyboards em nosssa wiki

## Resolve (Issues)

#10 -Storyboards

## Tasks
* Adição dos storyboards ao git

2020-08-31 13:23 UTC, gitgabiru approved these changes
Ficou muito bom Gabriel!!!

2020-08-31 13:23 UTC, micaellagouveia requested changes
Eu amei todos os storyboards, ficaram ótimos! Tem só uns errinhos de digitação mas ficou mt bom.

2020-08-31 13:23 UTC, micaellagouveia commented on docs/Elicitation/StoryBoard.md
> +| 30/08/2020 |  1.0   | Criação do documento e adição dos stroyboards criandos | Gabriel Davi |
Um errinho de digitação ali em criados está escrito criandos.

2020-08-31 13:23 UTC, micaellagouveia commented on docs/Elicitation/StoryBoard.md
> +![SB2](../assets/img/storyboards/SB2_GabrielDavi.png)
Tem um errinho de digitação no 2o quadro, todavia está escrito toda via.

2020-08-31 13:23 UTC, micaellagouveia commented on docs/Elicitation/StoryBoard.md
> +![SB1](../assets/img/storyboards/SB1_GabrielDavi.png)
Tem um errinho de digitação, no 2o quadro atualizá-la está escrito atualiza-lá.

2020-08-31 14:43 UTC, sofiapatrocinio approved these changes

2020-08-31 19:51 UTC, pedroeagle approved these changes

2020-09-01 00:28 UTC, micaellagouveia approved these changes

2020-09-01 00:29 UTC, merged