Template do Estudo Dirigido sobre Arq e Reutilização
UnBArqDsw/2020.1_G12_Stock pull request #184
Opened 2020-10-29 01:24 UTC by micaellagouveia

## Descrição 

Criação dos documentos dos estudos dessa sprint
Obs: Tá na branch dos meus estudos, então após dar merge, não apaguem a branch thanks :)

2020-10-30 12:50 UTC, GabrielDVpereira approved these changes

2020-10-30 22:25 UTC, sofiapatrocinio requested changes

2020-10-30 22:25 UTC, sofiapatrocinio commented on docs/Architecture/EstudoDirigido/parte1.md
> +* Estações de trabalho com bom poder de processamento, rodando aplicações locais, e sendo acessadas via interfaces gráficas.
Servidores tá escrito errado

2020-10-30 22:25 UTC, sofiapatrocinio commented on docs/Architecture/EstudoDirigido/parte1.md
> +* Estilo indicado para projeto mais simples. Quando complexos, os prjetos podem demandar soluções distribuídas, com comunicações entre clientes e servidores, P2P ou outro.
projetos tá escrito errado

2020-11-03 00:18 UTC, sofiapatrocinio approved these changes

2020-11-03 00:18 UTC, merged