Estudo Estilo Arquitetural parte 4
UnBArqDsw/2020.1_G12_Stock pull request #190
Opened 2020-11-02 20:22 UTC by pedroeagle

## Descrição 

Estudo das vídeo aulas e slides da parte 4 do módulo de estilo arquitetural de software.

## Resolve #181

2020-11-02 22:44 UTC, micaellagouveia requested changes

2020-11-02 22:44 UTC, micaellagouveia commented on docs/Index/architectureIndex.md
> +  - [Estilos e Padrões Arquiteturais - Parte 3](Architecture/EstudoDirigido/parte4.md)
Aqui a parte 3 está duplicada

2020-11-02 22:44 UTC, micaellagouveia commented on docs/Index/architectureIndex.md
> +  - [Visão Geral](Architecture/EstudoDirigido/geral.md)
Essa visão geral pode ser retirada.

2020-11-03 00:19 UTC, sofiapatrocinio approved these changes

2020-11-03 18:20 UTC, micaellagouveia approved these changes

2020-11-03 18:20 UTC, merged