171 reunião semanal
UnBArqDsw/2020.1_G12_Stock pull request #192
Opened 2020-11-03 20:01 UTC by sofiapatrocinio

## Descrição 

Documentação Sprint 9 e 10

## Resolve (Issues)

#171 e #185

2020-11-03 20:10 UTC, micaellagouveia approved these changes

2020-11-03 22:10 UTC, pedroeagle requested changes

2020-11-03 22:10 UTC, pedroeagle commented on docs/Sprints/planning/sprint10.md
> +| [**#187**](https://github.com/UnBArqDsw/2020.1_G12_Stock/issues/187)  | US05 - Adição e remoção de colaboradores  | 5 | Gabriel Davi e Pedro Igor |
as issues de implementação das US ficaram invertidas

2020-11-04 00:33 UTC, pedroeagle approved these changes

2020-11-04 00:33 UTC, merged