Add architecture study part 3
UnBArqDsw/2020.1_G12_Stock pull request #212
Opened 2020-11-16 14:47 UTC by micaellagouveia

## Descrição 

Dpcumentação dos estudos parte 3

## Resolve (Issues)

Issue #179

2020-11-16 18:31 UTC, GabrielDVpereira requested changes

2020-11-16 18:31 UTC, GabrielDVpereira commented on docs/Architecture/EstudoDirigido/parte3.md
> +| Facilita o entendimento de Todo e Parte |Difícil uso em aplicações iterativas, pois coloca em ênfase o mado "batch"|
"mado" => "modo"

2020-11-16 18:31 UTC, GabrielDVpereira commented on docs/Architecture/EstudoDirigido/parte3.md
> +* Muito utilizado quabdo um sistema demanda grande volume de informação, que precisa ser geradoe armazenado por um longo tempo.
"quabdo" => quando

2020-11-16 18:31 UTC, GabrielDVpereira commented on docs/Architecture/EstudoDirigido/parte3.md
> +* Muito utilizado quabdo um sistema demanda grande volume de informação, que precisa ser geradoe armazenado por um longo tempo.
"geradoe" => gerado

2020-11-17 00:21 UTC, sofiapatrocinio requested changes

2020-11-17 00:21 UTC, sofiapatrocinio commented on docs/Architecture/EstudoDirigido/parte3.md
> +| Manutenabilidade mais flexível | Pode ter deadlock com o uso de buffers finitos|
"manutenibilidade" tá escrito errado

2020-11-17 00:24 UTC, sofiapatrocinio approved these changes

2020-11-17 00:39 UTC, GabrielDVpereira approved these changes

2020-11-17 00:39 UTC, merged