204 reuniao semanal
UnBArqDsw/2020.1_G12_Stock pull request #213
Opened 2020-11-16 15:00 UTC by micaellagouveia

## Descrição 

Documentação da reunião semanal Sprint 12

## Resolve (Issues)

Issue #204

2020-11-16 18:34 UTC, GabrielDVpereira approved these changes

2020-11-17 00:15 UTC, sofiapatrocinio requested changes

2020-11-17 00:15 UTC, sofiapatrocinio commented on docs/Sprints/planning/sprint12.md
> +Alguns popntos foram levantados para serem feitos antes da entrega final como:
"pontos" tá escrito errado

2020-11-17 00:22 UTC, sofiapatrocinio approved these changes

2020-11-17 00:22 UTC, merged