9 entrevista
UnBArqDsw/2020.1_G12_Stock pull request #22
Opened 2020-08-31 18:10 UTC by GabrielDVpereira

Nesse pr foi feito
Issue #9 
Entrevista
Adição da entrevista e sua gravação em nosso repositório.

2020-08-31 18:55 UTC, pedroeagle requested changes
marquei umas pequenas correções. ficou muito bom mano! ela confirma basicamente todos os requisitos que levantamos na documentação até agr

2020-08-31 18:55 UTC, pedroeagle commented on docs/Elicitation/Entrevista.md
> +A entrevista foi realizada com Ivante Bezerra de 49 anos, que atualmente possui um empreendimento de pequeno porte chamado Bonnavita. O tipo de entrevista realizada foi fechada. A gravação para entre
ficou faltando um 'e' no nome da entrevistada

2020-08-31 18:55 UTC, pedroeagle commented on docs/Elicitation/Entrevista.md
> +A entrevista foi realizada com Ivante Bezerra de 49 anos, que atualmente possui um empreendimento de pequeno porte chamado Bonnavita. O tipo de entrevista realizada foi fechada. A gravação para entre
erro de digitação no 'a baixo', deveria ser:  "A gravação para entrevista está disponível abaixo bem como a transcrição da mesma."

2020-08-31 18:55 UTC, pedroeagle commented on docs/Elicitation/Entrevista.md
> +“Entorno de 10 mil por mês, é um negócio de pequeno porte”
"Em torno" no lugar de "Entorno"

2020-08-31 21:15 UTC, micaellagouveia requested changes
Nossa ficou muito boa a entrevista! Tem uns errinhos de digitação, mas nossa eu amei!

2020-08-31 21:15 UTC, micaellagouveia commented on docs/Elicitation/Entrevista.md
> +A entrevista é uma técnica de elicitação de requisitos que se baseia em questionar os stakeholders sobre processos e sistemas atuais e sobre o que é desejado para o que vai ser desenvolvido. Entrevis
Só trocar a introdução vem antes do histórico de revisões, para manter o padrão dos outros arquivos.

2020-08-31 21:15 UTC, micaellagouveia commented on docs/Elicitation/Entrevista.md
> +“Eu e meu sócio”
Faltou o ponto final.

2020-08-31 21:15 UTC, micaellagouveia commented on docs/Elicitation/Entrevista.md
> +“Entorno de 10 mil por mês, é um negócio de pequeno porte”
Faltou o ponto final.

2020-08-31 21:15 UTC, micaellagouveia commented on docs/Elicitation/Entrevista.md
> +“O meu termômetro é meu estoque. Atualmente, por exemplo, a gente fez uma compra grande. Também é pela demanda e pela carteira de cliente que a gente tem”
Faltou o ponto final.

2020-08-31 21:15 UTC, micaellagouveia commented on docs/Elicitation/Entrevista.md
> +“O estoque eu tabulei o saldo das minhas mercadorias e na medida que eu vou vendendo eu visito essa planilha e vou dando baixa lá. (não é a mesma planilha usada para a venda)”
Faltou o ponto final.

2020-08-31 21:15 UTC, micaellagouveia commented on docs/Elicitation/Entrevista.md
> +“A princípio não, a gente tem mantido o estoque adequado”
Faltou o ponto final.

2020-08-31 21:15 UTC, micaellagouveia commented on docs/Elicitation/Entrevista.md
> +“Já”
Faltou o ponto final.

2020-08-31 21:15 UTC, micaellagouveia commented on docs/Elicitation/Entrevista.md
> +“10. Não preciso de ajuda, eu tenho 32 anos de mercado de trabalho e trabalhando com computadores, então não tenho dificuldade alguma de lidar com tecnologia”
Faltou o ponto final.

2020-08-31 21:33 UTC, sofiapatrocinio approved these changes

2020-09-01 12:22 UTC, micaellagouveia approved these changes

2020-09-01 14:13 UTC, pedroeagle approved these changes

2020-09-01 14:36 UTC, merged