6 questionario
UnBArqDsw/2020.1_G12_Stock pull request #34
Opened 2020-09-05 14:08 UTC by pedroeagle

## Descrição 

Foi documentado o questionário escrito durante o design sprint.

## Resolve (Issues)

Resolve #6 

## Tarefas gerais realizadas
- [x] Criação do questionário no Forms
- [x]  Distribuição do questionário em grupos de vendas

2020-09-06 03:07 UTC, sofiapatrocinio requested changes

2020-09-06 03:07 UTC, sofiapatrocinio commented on docs/Elicitation/Questionario.md
> +O questionário é um método de elicitação de requisitos onde, por meio de perguntas estratégicas, é possível compreender melhor como o público de interesse reage a determinado assunto. Além disso, o q
Parágrafo duplicado

2020-09-06 03:07 UTC, sofiapatrocinio commented on docs/Elicitation/Questionario.md
> +As perguntas a seguir foram elaboradas em um dos dias de Design Sprint realizado pelo grupo. As perguntas foram escritas a princípio, individualmente por cada um dos membros do grupo, e discutidas em
Parágrafo duplicado

2020-09-06 03:07 UTC, sofiapatrocinio commented on docs/Elicitation/Questionario.md
> +(&nbsp;&nbsp;) entre 20 e 30<br>
Faltou a opção "Até 20 anos", já atualizei no forms

2020-09-06 03:07 UTC, sofiapatrocinio commented on docs/Elicitation/Questionario.md
> +**12** - Esta empresa já teve prejuízo por não controlar o estoque corretamente? (Produto passar da data de validade, produto não encontrado no estoque))<br>
Ao final, tem um parentêse a mais

2020-09-06 13:33 UTC, micaellagouveia requested changes
Ficou ótimo, tem só uma alteração na rota que precisa ser feita se não vai quebrar na master.

2020-09-06 13:33 UTC, micaellagouveia commented on docs/Index/baseIndex.md
> +    - [StoryBoard](../Elicitation/StoryBoard.md)
É necessário tirar os "../" pois no localhost ele aparece o documento, mas quando subimos pra master ele não encontra a página. Se deixar só Elicitation/nomedoArquivo.md, quando for para a master ele fará o caminho certo.

2020-09-06 13:33 UTC, micaellagouveia commented on docs/Index/baseIndex.md
> +    - [Mapa Mental](../Elicitation/MapaMental.md)
É necessário tirar os "../" pois no localhost ele aparece o documento, mas quando subimos pra master ele não encontra a página. Se deixar só Elicitation/nomedoArquivo.md, quando for para a master ele fará o caminho certo.

2020-09-06 13:33 UTC, micaellagouveia commented on docs/Index/baseIndex.md
> +    - [Entrevista](../Elicitation/Entrevista.md)
É necessário tirar os "../" pois no localhost ele aparece o documento, mas quando subimos pra master ele não encontra a página. Se deixar só Elicitation/nomedoArquivo.md, quando for para a master ele fará o caminho certo.

2020-09-06 13:33 UTC, micaellagouveia commented on docs/Index/baseIndex.md
> +    - [Brainstorming](../Elicitation/Brainstorming.md)
É necessário tirar os "../" pois no localhost ele aparece o documento, mas quando subimos pra master ele não encontra a página. Se deixar só Elicitation/nomedoArquivo.md, quando for para a master ele fará o caminho certo.

2020-09-06 13:33 UTC, micaellagouveia commented on docs/Index/baseIndex.md
> +    - [Questionário](../Elicitation/Questionario.md)
É necessário tirar os "../" pois no localhost ele aparece o documento, mas quando subimos pra master ele não encontra a página. Se deixar só Elicitation/nomedoArquivo.md, quando for para a master ele fará o caminho certo.

2020-09-06 13:33 UTC, micaellagouveia commented on temp/design sprint dia 1
> +queremos utilizar pq é uma ideia boa para uma solução rapida d eproelblmea
Onde posso encontrar esse documento? Ele precisa subir para a master?

2020-09-06 13:33 UTC, micaellagouveia commented on temp/minhas perguntas
> +Você trabalha em alguma empresa onde é necessário controlar o estoque de produtos?
Onde posso encontrar esse documento? Ele precisa subir para a master?

2020-09-06 13:33 UTC, micaellagouveia commented on temp/Questionário final
> +Questionário final:
Onde posso encontrar esse documento? Ele precisa subir para a master?

2020-09-06 17:42 UTC, micaellagouveia approved these changes

2020-09-06 19:49 UTC, sofiapatrocinio approved these changes

2020-09-07 05:02 UTC, gitgabiru approved these changes

2020-09-07 12:46 UTC, merged