16 estimativas
UnBArqDsw/2020.1_G12_Stock pull request #45
Opened 2020-09-07 02:32 UTC by GabrielDVpereira

## Descrição 

Documentação das estimativas

## Resolve (Issues)
Issue #16

2020-09-07 14:46 UTC, micaellagouveia requested changes
Ficou muito bom !!

2020-09-07 14:46 UTC, micaellagouveia commented on docs/Project/Evaluation.md
> +<<<<<<< HEAD
Tem que tirar essa linha 5 <<<<HEAD

2020-09-07 14:46 UTC, micaellagouveia commented on docs/Project/Evaluation.md
> +Devido as particularidades do projeto a equipe o classificou como **Semidestacado**, pois as funções básicas que o software irá realizar será a listagem de produtos por categoria no estoque, adição d
"adição de um produto no estoque e assim por diante. Não havendo ...". Essa parte ficaria melhor com uma vígula: "adição de um produto no estoque e assim por diante, não havendo ..".

2020-09-07 14:46 UTC, micaellagouveia commented on docs/Project/Evaluation.md
> +
Seria legal colocar no histórico de revisão como primeira versão o levantamento dessas linhas feitas por todos, para a Milene saber que todos participaram dessa etapa.

2020-09-07 14:46 UTC, micaellagouveia commented on docs/Project/Evaluation.md
> +Para 2270 linhas de código (2.27 Kloc)
Aqui está com a mesma quantidade de linhas da estimativa passada, mas com valores diferente.

2020-09-07 14:46 UTC, micaellagouveia commented on docs/Project/Evaluation.md
> +Para 2270 linhas de código (2.27 Kloc)
Aqui está com a mesma quantidade de linhas da estimativa passada, mas com valores diferente.

2020-09-07 14:46 UTC, micaellagouveia commented on docs/Project/Evaluation.md
> +Com isso, estipula-se que o valor total do projeto seja estimado em **R\$ 81,405.75** reais.
JESUIS AAAAAAAAAAAA

2020-09-07 14:46 UTC, micaellagouveia commented on docs/Project/Evaluation.md
> +=======
Remover essa linha 563.

2020-09-07 14:46 UTC, micaellagouveia commented on docs/Project/Evaluation.md
> +## Histórico de Revisão
Pq tem um histórico de revisão aqui embaixo?

2020-09-07 14:46 UTC, micaellagouveia commented on docs/Project/Evaluation.md
> +>>>>>>> b77ebae... Add evalutation documentation
Não entendi essa linha 569, ficou uma área em branco no documento.

2020-09-07 14:46 UTC, micaellagouveia commented on docs/_sidebar.md
> +  - [Estimativas](Project/Evaluation.md)
Show, só faltou colocar no index de projeto, para quando acessarmos pelo botão Projeto estar lá também. Tem que colocar no arquivo baseIndex.md dentro da pasta Index :)

2020-09-07 22:06 UTC, pedroeagle requested changes

2020-09-07 22:06 UTC, pedroeagle commented on docs/Project/Evaluation.md
> +| 05/09/2020 |  1.0   |       Abertura do documento de estimativas        | Gabriel Davi |
Acho que poderia adicionar no histórico de revisão o que fizemos em grupo detalhando o que produzimos e o nome de todo mundo, até pra fazer sentido o Design Sprint mencionado em cima

2020-09-08 00:30 UTC, GabrielDVpereira commented on docs/Project/Evaluation.md
> +Para 2270 linhas de código (2.27 Kloc)
Na vdd são diferentes, sendo a primeira 2770 e a outra 2270 (500 a menos) :)

2020-09-08 12:43 UTC, micaellagouveia approved these changes

2020-09-08 17:25 UTC, sofiapatrocinio approved these changes

2020-09-09 12:28 UTC, merged