31 causa efeito
UnBArqDsw/2020.1_G12_Stock pull request #46
Opened 2020-09-07 04:54 UTC by gitgabiru

## Descrição 

Documentação dos diagramas de causa e efeito

## Resolve (Issues)

#31 

## Tarefas gerais realizadas
* Diagramas de causa e efeito
* Tabelas com as informações dos diagramas em forma de texto

2020-09-07 12:21 UTC, pedroeagle requested changes
Só esse detalhe mínimo que mencionei. O documento está muito bom!

2020-09-07 12:21 UTC, pedroeagle commented on docs/preTraceability/causaEfeito.md
> +O diagrama Causa e Efeito, conhecido também como diagrama Ishikawa ou Espinha de peixe é uma forma de levantar os fatores/causas que levam á um determinado efeito, seja ele positivo ou negativo, afim
saiu um acento no "os fatores/causas que levam á". o correto seria "os fatores/causas que levam á".

2020-09-07 12:54 UTC, GabrielDVpereira reviewed
Posso estar me confundindo, mas não havia também uma parte no qual a gente detalhava as medida que iremos tomar baseado nas causas negativas?

2020-09-07 13:02 UTC, GabrielDVpereira reviewed
Também acho que seria interessante separar em tópicos os de causa e efeito positivos e negativos

2020-09-07 15:00 UTC, micaellagouveia requested changes

2020-09-07 15:00 UTC, micaellagouveia commented on docs/preTraceability/causaEfeito.md
> +O diagrama Causa e Efeito, conhecido também como diagrama Ishikawa ou Espinha de peixe é uma forma de levantar os fatores/causas que levam á um determinado efeito, seja ele positivo ou negativo, afim
Faltou ums vírgula em: ... também como diagrama Ishikawa ou Espinha de peixe, é uma forma ...

2020-09-07 15:00 UTC, micaellagouveia commented on docs/preTraceability/causaEfeito.md
> +O diagrama Causa e Efeito, conhecido também como diagrama Ishikawa ou Espinha de peixe é uma forma de levantar os fatores/causas que levam á um determinado efeito, seja ele positivo ou negativo, afim
Afim neste caso é separado: a fim.

2020-09-07 15:00 UTC, micaellagouveia commented on docs/_sidebar.md
> +    - [Diagrama Causa e Efeito](preTraceability/causaEfeito.md)
Show, só faltou colocar no index de Base, tem que colocar no arquivo baseIndex que ta na pasta Index.

2020-09-07 15:01 UTC, sofiapatrocinio commented
Só senti falta de padronização de cores e fontes, mas depois a gente faz outra versão. Tá top!

2020-09-07 15:01 UTC, sofiapatrocinio approved these changes

2020-09-07 15:57 UTC, pedroeagle approved these changes

2020-09-08 12:49 UTC, micaellagouveia approved these changes

2020-09-08 12:49 UTC, merged