39 introspeccao personas
UnBArqDsw/2020.1_G12_Stock pull request #53
Opened 2020-09-10 12:55 UTC by micaellagouveia

## Descrição 

Criação das personas e uso da introspecção.

## Resolve (Issues)

Issue #39 

## Tarefas gerais realizadas
* Criação das personas
* Criação do documento de introspecção
* Elicitação dos requisitos segundo as personas

2020-09-10 13:08 UTC, GabrielDVpereira approved these changes

2020-09-10 13:14 UTC, sofiapatrocinio requested changes

2020-09-10 13:14 UTC, sofiapatrocinio commented on docs/Elicitation/Introspeccao.md
> +A introspecção é uma é uma técnica muito utilizada na etapa de elicitação de requisitos. Ela tem como objetivo em entender as funcionalidades importantes de um sistema. Apesar de muito usada, nem sem
" Ela tem como objetivo em entender as funcionalidades importantes de um sistema." não tem necessidade desse "em"

2020-09-10 13:14 UTC, sofiapatrocinio commented on docs/Elicitation/Introspeccao.md
> +Para o uso da técnica, utilizamos as personas criadas como base do nosso usuário. Com isso, evitamos a falha desta técnica, pois os requisitos levantados serão retirados e pensados na visão do usuári
"Para o uso da técnica, utilizamos as personas criadas como base do nosso usuário." essa frase tá estranha como base do nosso usuário?

2020-09-10 13:14 UTC, sofiapatrocinio commented on docs/Elicitation/Introspeccao.md
> +Para o uso da técnica, utilizamos as personas criadas como base do nosso usuário. Com isso, evitamos a falha desta técnica, pois os requisitos levantados serão retirados e pensados na visão do usuári
"descritos nas personas que possuímos", acho que ficaria melhor "com base nas personas", descritos nas dá ideia de onde vai ser descrito e não com base em quem

2020-09-10 19:48 UTC, sofiapatrocinio approved these changes

2020-09-10 19:49 UTC, sofiapatrocinio requested changes

2020-09-10 19:49 UTC, sofiapatrocinio commented on docs/Elicitation/Introspeccao.md
> +A introspecção é uma é uma técnica muito utilizada na etapa de elicitação de requisitos. Ela tem como objetivo entender as funcionalidades importantes de um sistema. Apesar de muito usada, nem sempre
"é uma" tá escrito duas vezes

2020-09-10 19:50 UTC, sofiapatrocinio requested changes

2020-09-10 19:50 UTC, sofiapatrocinio commented on docs/Elicitation/Personas.md
> +Hoje as personas são uma das principais ferramentas de planejamento para as aplicações que centram suas estratégias no usuário. Para o projeto, o time decidiu criar personas baseadas em pessoas conhe
"utilizado" tá escrito errado

2020-09-11 00:09 UTC, sofiapatrocinio approved these changes

2020-09-11 00:09 UTC, merged