71 entrevista
UnBArqDsw/2020.1_G12_Stock pull request #82
Opened 2020-09-16 02:51 UTC by gitgabiru

## Descrição 

Foram realizados mais duas entrevistas.

## Resolve (Issues)

#71 Entrevista - evolução

## PRs relacionados, se houver

## Tarefas gerais realizadas
* Entrevista
* Digitação da entrevista
* Possíveis Requisitos levantados
* Possíveis Léxicos levantados

2020-09-16 03:05 UTC, GabrielDVpereira requested changes

2020-09-16 03:05 UTC, GabrielDVpereira commented on docs/Elicitation/Entrevistas/entrevista5.md
> +"Compraria peli feeling mesmo, atualmente não tem como saber."
peli -> pelo

2020-09-16 14:37 UTC, micaellagouveia requested changes
Ficou excelente galera! Só uns errinhos que pontuei mas é rapidinho pra resolver

2020-09-16 14:37 UTC, micaellagouveia commented on docs/Elicitation/Entrevistas/entrevista4.md
> +"Mais na questão de controle de produção e administrativo. Administrar a produção, quanto tempo leva a produção de cada um dos [produtos](Modeling/objeto?id=Produto). Ás vezes acredita-se que é possí
Às vezes está escrito com acento errado.

2020-09-16 14:37 UTC, micaellagouveia commented on docs/Elicitation/RequisitosElicitados.md
> +| Consulta de [produtos](Modeling/objeto?id=Produto) mais vendidos | **RF24** | O sistema deve ser capaz de informar os [produtos](Modeling/objeto?id=Produto) que mais estão saindo do [estoque](Model
O backward do requisito 24 está sem o link para a Entrevista.

2020-09-16 14:37 UTC, micaellagouveia commented on docs/Elicitation/Entrevistas/entrevista5.md
> +" ----- "
Essa pergunta pode não ser respondida mesmo, aí vc pode colocar o mesmo texto que está na entrevista 2.

2020-09-16 14:37 UTC, micaellagouveia commented on docs/Elicitation/Entrevistas/entrevista5.md
> +### 9. Já aconteceu de você se enganar quanto ao número de [produtos](Modeling/objeto?id=Produto) que possui em [estoque](Modeling/objeto?id=Estoque)?
faltou ponto final

2020-09-16 14:37 UTC, micaellagouveia commented on docs/Elicitation/Entrevistas/entrevista5.md
> +### 12. Qual a maior dificuldade que você enfrenta na parte administrativa de seu negócio?
faltou ponto final

2020-09-16 14:37 UTC, micaellagouveia commented on docs/Elicitation/Entrevista.md
> +### [*Entrevista 4 - Ricardo](Elicitation/Entrevistas/entrevista4.md)
Faltou a idade do Ricardo, mas se não tiver essa informação, tudo bem.

2020-09-16 14:37 UTC, micaellagouveia commented on docs/Elicitation/Entrevista.md
>  ## Requisitos Totais levantados
Faltou colocar os requisitos novos elencados como o: 23 e 24.

2020-09-16 20:10 UTC, sofiapatrocinio approved these changes, later dismissed

2020-09-17 02:19 UTC, micaellagouveia commented
Meninos, os novos requisitos estão dando conflito pois o pr de questionário também veio com requisito novo. Tem q mudar a numeração.

2020-09-17 13:41 UTC, micaellagouveia requested changes
Ficou faltando só umas referências dos léxicos e alterar o número deles em uns documentos.

2020-09-17 13:41 UTC, micaellagouveia commented on docs/Elicitation/Entrevistas/entrevista4.md
> +| [#RF23](Elicitation/RequisitosElicitados.md?id=requisitos-funcionais)  | Registrar valor do [produto](Modeling/objeto?id=Produto) |
Esses requisitos 23 e 24 na verdade são os 25 e 26

2020-09-17 13:41 UTC, micaellagouveia commented on docs/Elicitation/Entrevistas/entrevista5.md
> +| [#RF24](Elicitation/RequisitosElicitados.md?id=requisitos-funcionais)  | Consulta de [produtos](Modeling/objeto?id=Produto) mais vendidos |
Este requisito 24 na verdade é o 26

2020-09-17 13:41 UTC, micaellagouveia commented on docs/Elicitation/Entrevista.md
>  ## Requisitos Totais levantados
Nesta página ficou faltando colocar os novos requisitos elicitados pelas entrevistas, que são os requisitos 25  e 26

2020-09-17 14:13 UTC, GabrielDVpereira approved these changes

2020-09-17 14:54 UTC, micaellagouveia approved these changes

2020-09-17 14:54 UTC, merged