87 especificacao suplementar
UnBArqDsw/2020.1_G12_Stock pull request #97
Opened 2020-09-21 12:15 UTC by pedroeagle

## Descrição 

Criação do documento de especificação suplementar.

## Resolve #87 

## Tarefas gerais realizadas
- [x] Estar documentado na Wiki

2020-09-21 12:24 UTC, sofiapatrocinio requested changes

2020-09-21 12:24 UTC, sofiapatrocinio commented on docs/Modeling/EspecificacaoSuplementar.md
> +Esta especificação tem por finaliadade apresentar os [requisitos não funcionais](/Modeling/objeto?id=requisito-não-funcional) do sistema de controle de [estoque](/Modeling/objeto?id=estoque), Stock.
"finalidade" está escrito errado

2020-09-21 12:24 UTC, sofiapatrocinio commented on docs/Modeling/EspecificacaoSuplementar.md
> +A aplicação [web](/Modeling/objeto?id=web-app), Stock deverá ser capaz de gerenciar o [estoque](/Modeling/objeto?id=estoque) de [micro e pequenas empresas](/Modeling/objeto?id=micro-empresa). Um [sóc
O link de papéis está quebrado e acho que nem se encaixa nesse léxico, porque papéis dos colaboradores é a função que desempenham na empresa

2020-09-21 12:24 UTC, sofiapatrocinio commented on docs/Modeling/EspecificacaoSuplementar.md
> +Esta especificação tem por finaliadade apresentar os [requisitos não funcionais](/Modeling/objeto?id=requisito-não-funcional) do sistema de controle de [estoque](/Modeling/objeto?id=estoque), Stock.
"Controle de estoque" é um léxico

2020-09-21 12:24 UTC, sofiapatrocinio commented on docs/Modeling/EspecificacaoSuplementar.md
> +A aplicação deve ser compatível com qualquer [navegador](/Modeling/objeto?id=navegador) [web](/Modeling/objeto?id=web-app) assim como [pwa](/Modeling/objeto?id=pwa), para utilização de qualquer, ou a
PWA é uma sigla, melhor deixá-la maiúscula

2020-09-21 12:45 UTC, micaellagouveia approved these changes, later dismissed
Ficou excelente!!!

2020-09-21 14:10 UTC, GabrielDVpereira requested changes
Mto mto bom

2020-09-21 14:10 UTC, GabrielDVpereira commented on docs/Modeling/EspecificacaoSuplementar.md
> +## [Requisitos](/Modeling/objeto?id=requisito-não-funcional) de Licenciamento
Linkar lexicos com ## quebra no preview do tópico no sidebar

2020-09-22 01:24 UTC, sofiapatrocinio approved these changes

2020-09-22 11:39 UTC, micaellagouveia approved these changes

2020-09-22 11:39 UTC, merged